[package]
name = "sma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.prod]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = true


[dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
path-clean = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shlex = "1.1"
thiserror = "1.0"
