[package]
name = "sma"
version = "0.1.0"
edition = "2021"
authors = ["Gabriel"]
rust-version = "1.68.1"
readme = "README.md"
repository = "https://github.com/GabbeHags/sma"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.prod]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = true


[dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
eframe = "0.21"
path-clean = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shlex = "1.1"
sysinfo = "0.28"
thiserror = "1.0"
